# Generated by Django 3.2.19 on 2023-05-20 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='censo',
            name='discapacidad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='censo',
            name='isGeneral',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('idzona', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantmujeres', models.IntegerField()),
                ('cantHombres', models.IntegerField()),
                ('localidad', models.CharField(max_length=50)),
                ('isUrbano', models.BooleanField()),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadisticos.censo')),
            ],
        ),
    ]
