# Generated by Django 3.2.19 on 2023-05-20 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticos', '0002_auto_20230519_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLocalidad',
            fields=[
                ('idtipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='zona',
            name='isUrbano',
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('idlocalidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('isUrbano', models.BooleanField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadisticos.tipolocalidad')),
            ],
        ),
    ]
