# Generated by Django 3.2.19 on 2023-05-20 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticos', '0003_auto_20230520_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadisticos.localidad'),
        ),
    ]
