# Generated by Django 3.2.19 on 2023-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticos', '0004_alter_zona_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='censo',
            name='descripcion',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
